package numberguessinggame;

import java.text.NumberFormat;
import java.util.Random;
import javax.swing.JFormattedTextField;
import javax.swing.text.NumberFormatter;

/**
 * Class in which contents of GUI are handled
 *
 * @author kritterbusch
 */
public class GameDisplayWindow extends javax.swing.JFrame {

    int num;
    Random randomNum = new Random();
    int randNum = randomNum.nextInt(20) + 1;

    private GuessingGameService guessingGame;

    /**
     * Creates new form GameDisplayWindow
     */
    public GameDisplayWindow() {
        initComponents();
        guessingGame = new GuessingGameService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameTitleHeader1 = new javax.swing.JLabel();
        txtNumEntry = new javax.swing.JTextField();
        txtEnterGuess = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        txtInstructions = new javax.swing.JLabel();
        btnPlayAgain = new javax.swing.JButton();
        lblOutputMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gameTitleHeader1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gameTitleHeader1.setForeground(new java.awt.Color(102, 0, 102));
        gameTitleHeader1.setText("Awesome Guessing Game");

        txtNumEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumEntryActionPerformed(evt);
            }
        });

        txtEnterGuess.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEnterGuess.setText("Enter your guess");

        goButton.setText("GO!");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        txtInstructions.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtInstructions.setText("Enter a number between 1 and 20");

        btnPlayAgain.setText("Play Again");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });

        lblOutputMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOutputMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(txtEnterGuess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnPlayAgain))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(goButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(gameTitleHeader1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(txtInstructions)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(gameTitleHeader1)
                .addGap(18, 18, 18)
                .addComponent(txtInstructions)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnterGuess))
                .addGap(18, 18, 18)
                .addComponent(goButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOutputMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPlayAgain)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumEntryActionPerformed
        String number = txtNumEntry.getText();
        int num = Integer.valueOf(number);

    }//GEN-LAST:event_txtNumEntryActionPerformed

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
    
        String msg = "";
        lblOutputMessage.setText(msg);
        txtNumEntry.setText(msg);
        Random randomNum = new Random();
        randNum = randomNum.nextInt(20) + 1;
        goButton.setEnabled(true);
        
        

    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed

try {
        num = Integer.parseInt(txtNumEntry.getText());
    } catch (NumberFormatException nfe) {
        txtNumEntry.setText("");
    }

        
//        num = Integer.valueOf(txtNumEntry.getText());
         
        
        if (num < 1 || num > 20) {
            String msg = num + " is out of bounds. Read the instructions, moron.";
            lblOutputMessage.setText(msg);
        } else if (num < randNum) {
            String msg = num + " is too low, guess again";
            lblOutputMessage.setText(msg);

        } else if (num > randNum) {
            String msg = num + " is too high, guess again";
            lblOutputMessage.setText(msg);
        } else {
            String msg = "You guessed the correct number! " + randNum + " it was!";
            lblOutputMessage.setText(msg);
            
            goButton.setEnabled(false);

        }
    }//GEN-LAST:event_goButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JLabel gameTitleHeader1;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel lblOutputMessage;
    private javax.swing.JLabel txtEnterGuess;
    private javax.swing.JLabel txtInstructions;
    private javax.swing.JTextField txtNumEntry;
    // End of variables declaration//GEN-END:variables
}
